name: Matrix Stratagies Demo
on:
    push:
        branches:
            - 'main'
    workflow_dispatch:
jobs:
     build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 14, 17]
                operating-system: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.operating-system }}    # ubuntue-24.04
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: build application
              run: npm run build