name: Matrix Stratagies Demo
on:
    push:
        branches:
            - 'main'
    workflow_dispatch:
jobs:
     build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 16]
                operating-system: [ubuntu-24.04, windows-latest]
                include:
                  - node-version: 18
                    operating-system: ubuntu-latest
                exlude:
                  - node-version: 12
                    operating-system: windows-latest
        runs-on: ${{ matrix.operating-system }}    # ubuntue-24.04
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: build application
              run: npm run build