name: Matrix Stratagies Demo
on:
    push:
        branches:
            - 'main'
    workflow_dispatch:
jobs:
     build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 14, 17]
                operating-system: [ubuntu-latest, windows-lates]
        runs-on: ${{ matrix.operating-system }}    # ubuntue-24.04
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Caching Dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: node_modules
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: build application
              run: npm run build